# Generated by Django 4.2.3 on 2023-08-14 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_post_receiver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('finance', '금융'), ('쇼핑', 'shopping'), ('문서 및 이메일 작성', 'document and email writing'), ('영상 및 사진', 'video and photo'), ('예약 및 예매', 'reservation and booking'), ('기기고장', 'device breakdown'), ('인터넷', 'internet'), ('기타', 'etc')], max_length=20),
        ),
    ]
