# Generated by Django 4.2.3 on 2023-08-14 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_post_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('finance', '금융'), ('shopping', '쇼핑'), ('document_and_email', '문서 및 이메일 작성'), ('video_and_photo', '영상 및 사진'), ('reservation_and_booking', '예약 및 예매'), ('device_breakdown', '기기고장'), ('internet', '인터넷'), ('etc', '기타')], max_length=25),
        ),
    ]
